### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by PolygonError** [shrimqy/Seki#1]
I'm unable to build the project as it is right now.
Seems like a few folders are missing that are defined in the project file?

![image](https://github.com/user-attachments/assets/673d3c2d-1b29-4ea8-9d44-568b36e6b4f8)
Main failure right now preventing the build compiling is [this line](https://github.com/shrimqy/Seki/blob/f58c30d614efe4089e310b043a8c9883c65b96a4/src/Seki.App/Utils/MessageHandler.cs#L88)
`The name 'CommandService' does not exist in the current context`

I assume it references something in the missing folders.

**Comment by shrimqy** [comment]
You can just remove that line, I kept that line for a future feature, but I
think I forgot to add the rest of the code mb.
And as for the folders, you can delete the references to it from the
manifest.
The code base requires a lot of refactoring sorry.

**Comment by shrimqy** [comment]
Refactored the codebase to fix the build issues.
