### ISSUE TITLE
program doesnt exist on the windows store

### ISSUE THREAD

**Issue by osteocatitisemia** [shrimqy/Seki#2]
this project seems very interesting and id like to test it out but being unavailable on the ms store and having no other way to install it i cant test it
![image](https://github.com/user-attachments/assets/5a060ace-245a-45b5-8c26-6b795ab89167)

**Comment by shrimqy** [comment]
It was recently removed from the store, but I had already gave an appeal and resubmitted but it is yet to be certified. Try this [link ](https://apps.microsoft.com/detail/9pjv6d1jpg0h?launch=true&mode=full&hl=en-us&gl=IN) to see if it working (it appears to be working on my end) or 

Download the packages and certifcates from [Drive](https://drive.google.com/drive/u/4/folders/1DcjlZteJkj067erkfgd9pWoFBM9Icb_G)

you have to open the file with .cer extension and when you do install the certificate be sure to choose store location as local machine and place all certificates in the following store and choose
personal
trusted root certification authorities
trusted People that should all be it, now you can install the app ig (if not tell me)

**Comment by spyder52** [comment]
It is working for me, just downloaded from Windows Store. But having another problem actually getting my 2 devices to talk to each other with the app...

**Comment by shrimqy** [comment]
> It is working for me, just downloaded from Windows Store. But having another problem actually getting my 2 devices to talk to each other with the app...

The current Windows store version is 0.2.1, the latest 0.3.1 is yet to be certified. You will have to use the same version of the android app as well. Previous versions had some problems yes, it will be great if you can give me a log. Also make sure you're not using a virtual adapter (it will be fixed next version).

**Comment by shrimqy** [comment]
I will be closing this as the app is back on store.
