### ISSUE TITLE
Bug: Connection problem

### ISSUE THREAD

**Issue by shrimqy** [shrimqy/Seki#3]
It is working for me, just downloaded from Windows Store. But having another problem actually getting my 2 devices to talk to each other with the app...

_Originally posted by @spyder52 in https://github.com/shrimqy/Seki/issues/2#issuecomment-2381582619_

**Comment by spyder52** [comment]
Android app finds with windows device in the local network but clicking it does not provide any connection. Just loops me back to trying to connect again.

**Comment by shrimqy** [comment]
Could you provide more details, App version you are using for both windows and android, android os version. Logcat would be really helpful too.

**Comment by spyder52** [comment]
Sekia v0.3.1 - Android 14 - S23+ OneUI 6.1
Seki v0.2.1 - Windows 11
[sekia_logcat.txt](https://github.com/user-attachments/files/17187080/sekia_logcat.txt)

**Comment by shrimqy** [comment]
Can you update the windows verison to the latest v0.3.1 as well and check again? Also the logcat seems to be filtered out and doesn't seem to show the correct logs, make sure you're in debug mode when getting the logs.

**Comment by spyder52** [comment]
Shall try, downloaded from windows store last night and it gave me the v0.2.1.. so thought was the latest

**Comment by spyder52** [comment]
That worked. Thanks
